
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "chatbot-global-lb-frontend" {
  source                          = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v13.2.0"
  name                            = "chatbot-lb-frontend"
  project_id                      = var.chatbot-global-lb-frontend_project_id
  url_map_input                   = module.chatbot-global-lb-backend.backend_service_info
  ssl                             = true
  managed_ssl_certificate_domains = ["plenainformatica.com.br"]
}
module "chatbot-global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "chatbot-lb-backend"
  project_id = var.chatbot-global-lb-backend_project_id
  serverless_neg_backends = [{
    region          = module.chatbot-frontend-service.location
    service_name    = module.chatbot-frontend-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
}
module "chatbot-frontend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = var.chatbot-frontend-service_project_id
  location                      = "us-central1"
  service_name                  = "chatbot-frontend"
  containers                    = [{"container_name" = "service-container", "env_vars" = {"BACKEND_URL" = module.chatbot-backend-service.service_uri}, "ports" = {"container_port" = 80}, "container_image" = "gcr.io/${var.project_id}/chatbot-frontend:latest"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "chatbot-backend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = var.chatbot-backend-service_project_id
  location                      = "us-central1"
  service_name                  = "chatbot-backend"
  containers                    = [{"container_image" = "gcr.io/${var.project_id}/chatbot-backend:latest", "container_name" = "service-container", "env_secret_vars" = {"DB_PASSWORD" = module.chatbot-database-secret.env_vars.SECRET}, "env_vars" = {"DB_SOCKET_PATH" = "/cloudsql/${module.chatbot-database-postgresql.instance_connection_name}", "CLOUD_SQL_CONNECTION_NAME" = module.chatbot-database-postgresql.instance_connection_name, "DB_HOST" = module.chatbot-database-postgresql.instance_first_ip_address, "DB_NAME" = module.chatbot-database-postgresql.env_vars.CLOUD_SQL_DATABASE_NAME, "PROJECT_ID" = var.project_id}, "ports" = {"container_port" = 8080}, "volume_mounts" = [{"name" = "cloudsql", "mount_path" = "/cloudsql"}]}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/aiplatform.user"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_ONLY"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    chatbot_vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "chatbot-database-postgresql" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = var.chatbot-database-postgresql_project_id
  region                      = "us-central1"
  name                        = "chatbot-db"
  edition                     = "ENTERPRISE"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-custom-2-7680"
  deletion_protection_enabled = false
  disk_autoresize             = true
  disk_size                   = 50
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = [{
    email = module.chatbot-backend-service.service_account_id.email
    id    = module.chatbot-backend-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
}
module "chatbot-database-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = var.chatbot-database-secret_project_id
  name        = "chatbot-db-secret"
  secret_data = module.chatbot-database-postgresql.generated_user_password
}
module "chatbot-vertex-ai" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = var.chatbot-vertex-ai_project_id
  activate_apis = ["aiplatform.googleapis.com"]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat(module.chatbot-global-lb-frontend.apphub_service_uri, module.chatbot-global-lb-backend.apphub_service_uri, [module.chatbot-frontend-service.apphub_service_uri], [module.chatbot-backend-service.apphub_service_uri], [module.chatbot-database-postgresql.apphub_service_uri])
  application_id = var.apphub_application_id
}
