
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "chatbot-global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.chatbot-global-lb-frontend.external_ip
}
output "chatbot-global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.chatbot-global-lb-frontend.external_ipv6_address
}
output "chatbot-global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.chatbot-global-lb-frontend.ip_address_internal_managed_http
}
output "chatbot-global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.chatbot-global-lb-frontend.ip_address_internal_managed_https
}
output "chatbot-frontend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.chatbot-frontend-service.service_uri
}
output "chatbot-backend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.chatbot-backend-service.service_uri
}
