
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "chatbot-global-lb-frontend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "chatbot-global-lb-backend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "chatbot-frontend-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "chatbot-backend-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "chatbot-database-postgresql_project_id" {
  description = "The project ID to manage the Cloud SQL resources"
  type = string
}
variable "chatbot-database-secret_project_id" {
  description = "The project ID to manage the Secret Manager resources"
  type = string
}
variable "chatbot-vertex-ai_project_id" {
  description = "The GCP project you want to enable APIs on"
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
